version: '3'
services:
  paradise-api:
    image: nelson59/paradise-api:latest
    ports:
      - "8080:80"
      - "9000:9000"  # Xdebug
    volumes:
      - .:/var/www/html # persistance for dev
    networks:
      - paradise-network
  
  paradise-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - ./Database:/docker-entrypoint-initdb.d
    networks:
      - paradise-network

networks:
  paradise-network: