name: Build ans Deploy

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'

    - name: Install dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Build Docker image
      run: docker build -t nelson59/paradise-api:latest .

    - name: Push Docker image to registry
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin && docker push nelson59/paradise-api:latest

    - name: SSH into server and pull the latest image
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}SSH_PRIVATE_KEY
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker-compose down
          docker-compose rm
          docker-compose pull
          docker-compose up -d
